spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  servlet:
    context-path: /api/lms3
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: 500MB

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_SECRET_KEY}
