spring.datasource.url=${AIVEN_URL}
spring.datasource.username=avnadmin
spring.datasource.password = ${AIVEN_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SSL for Aiven
spring.datasource.hikari.data-source-properties.sslMode=REQUIRED